### ISSUE TITLE
Auto close IW when another marker is clicked

### ISSUE THREAD

**Issue by scoco** [furcan/Markers-On-Map#1]
Hello,

I applied a fix for a project so that when an infowindow opens, the others close when clicking on a marker.

> /dist/markers-on-map-1.4.0.js

Delete `var momInfoWindow;` line 419
Add `var momInfoWindow = null;` line 99

See you soon on the web

**Comment by furcan** [comment]
Hi,
Thank you for the suggestion.
I have designed the info window element to show multiple info windows. 

I will add (ASAP) an init option that will prevent multiple info windows. 

Thanks.

Furkan.
